//layout.
import { Provider } from 'react-redux';
import './globals.css';
import Providers from '../commonComponents/Provider.jsx';
export const metadata = {
  title: 'Quotation Management',
  description: 'Generated by Next.js',
}


export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Providers>
          {children}
        </Providers>
      </body>
    </html>
  );
}
