import './globals.css';
import { Toaster } from "react-hot-toast";
export const metadata = {
  title: 'Quotation Management',
  description: 'Generated by Next.js',
}


export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
      <Toaster position="bottom-center" />
          {children}
      </body>
    </html>
  );
}
