//layout.
import { Provider } from 'react-redux';
import '../globals.css'
import Providers from '../components/commonComponents/Provider.jsx';
export const metadata = {
  title: 'Qms Tool',
  description: 'Generated by Next.js',
}


export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        {/* Add favicon here */}
        <link rel="icon" href="/fev.png" />
      </head>
      <body>
        <Providers>
          {children}
        </Providers>
      </body>
    </html>
  );
}
